apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: bezerrajs/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
